version: "3.8"

services:
  nginx:
    container_name: web_nginx
    build: ./nginx
    image: owasp/modsecurity-crs:nginx-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - BACKEND=http://app:8080
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - SEC_RULE_ENGINE=On
      - AUDIT_ENGINE=RelevantOnly
      - AUDIT_LOG_FORMAT=JSON
      - MODSEC_AUDIT_LOG_TYPE=Serial
      - MODSEC_AUDIT_LOG=/var/log/modsecurity/audit.log
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/custom:/etc/modsecurity.d/owasp-crs/rules:ro
    depends_on:
      - app
    networks:
      - app-net

  app:
    container_name: web_app
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-net

  mysql:
    container_name: web_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
