version: "3.8"

services:
  nginx:
    container_name: web_nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"  # Chỉ cần port 80
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - BACKEND=http://app:8080
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - SEC_RULE_ENGINE=On
    volumes:
      - ./nginx/custom:/etc/modsecurity.d/owasp-crs/rules:ro
      - ./nginx/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf:ro
      - modsec_logs:/var/log/modsecurity
    depends_on:
      - app
    networks:
      - app-net

  app:
    container_name: web_app
    build: .
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-net

  mysql:
    container_name: web_mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app-net

volumes:
  mysql_data:
  modsec_logs:

networks:
  app-net:
    driver: bridge